import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Typography from "@/app/_components/atoms/Typography";
import Link from "next/link";
import type { FC, PropsWithChildren } from "react";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
	return (
		<html lang="ko">
			<body style={inter.style} className="mx-auto my-0 max-w-[600px] p-2">
				<Link href="/">
					<Typography as="h2" className="p-2 text-center">
						TODO LIST
					</Typography>
				</Link>
				{children}
			</body>
		</html>
	);
};

export default RootLayout;
